tasks:
  - name: Start Kafka Cluster
    init: |
      docker-compose -f docker-compose.yaml up -d
    command: |
      docker-compose -f docker-compose.yaml logs -f
  
  - name: Create Admin User
    init: |
      until docker-compose -f docker-compose.yaml exec broker1 bash -c "kafka-topics.sh --bootstrap-server localhost:9094 --list" >/dev/null 2>&1; do
        echo "Waiting for broker1 to be ready..."
        sleep 3
      done
      docker-compose -f docker-compose.yaml exec broker1 bash -c "kafka-configs.sh --bootstrap-server localhost:9094 --alter --add-config 'SCRAM-SHA-256=[iterations=8192,password=admin-secret]' --entity-type users --entity-name admin"
    command: |
      echo "Admin user created with SCRAM-SHA-256 authentication. username: admin, password: admin-secret"

ports:
  - port: 9092
    description: Kafka Broker 1

  - port: 9093
    description: Kafka Broker 2

  - port: 9094
    description: Kafka Broker 3