version: "3.8"

x-common-env: &common-env
  PATH: "$PATH:/opt/kafka/bin"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT
  KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
  KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/config/jaas.conf
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
  KAFKA_SUPER_USERS: User:admin
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

services:
  controller-1:
    image: apache/kafka:latest
    container_name: controller-1
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
    volumes:
      - ./config:/etc/kafka/config

  controller-2:
    image: apache/kafka:latest
    container_name: controller-2
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
    volumes:
      - ./config:/etc/kafka/config

  controller-3:
    image: apache/kafka:latest
    container_name: controller-3
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
    volumes:
      - ./config:/etc/kafka/config

  broker-1:
    image: apache/kafka:latest
    container_name: broker-1
    ports:
      - 9092:9092
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092,PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092,PLAINTEXT://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
    depends_on:
      - controller-1
      - controller-2
      - controller-3
    volumes:
      - ./config:/etc/kafka/config

  broker-2:
    image: apache/kafka:latest
    container_name: broker-2
    ports:
      - 9093:9092
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
    depends_on:
      - controller-1
      - controller-2
      - controller-3
    volumes:
      - ./config:/etc/kafka/config

  broker-3:
    image: apache/kafka:latest
    container_name: broker-3
    ports:
      - 9094:9092
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
    depends_on:
      - controller-1
      - controller-2
      - controller-3
    volumes:
      - ./config:/etc/kafka/config
